services:
  resaletelegrambot:
    image: resaletelegrambot
    build:
      context: .
      dockerfile: ResaleTelegramBot/Dockerfile
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8080:8080"
    platform: linux/amd64

  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=ResaleBot
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - ./.containers/database:/var/lib/postgresql/data